---
galaxy_info:
  author: John Dewey
  description: Test SC role
  license: MIT
  min_ansible_version: 2.2
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags: []
dependencies: []
